### ISSUE TITLE
Plugin won’t start, Error: Could not locate the bindings file.

### ISSUE THREAD

**Issue by jph76** [plhyhc/homebridge-garage-door-wsensor#12]
Dear Developer,

I’m trying to get your plugin to run on a Pi Zero with Raspbian 11 Lite, Homebridge installed from repository following instructions from https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Raspbian

Configuration is as follows:

```
{
    "bridge": {
        (omitted)
    },
    "accessories": [
        {
            "accessory": "Garage Door Opener",
            "name": "Garage Door",
            "doorRelayPin": 11,
            "doorSensorPin": 16,
            "invertDoorState": false,
            "invertSensorState": false,
            "duration_ms": 500
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        }
    ],
    "disabledPlugins": []
}
```

Basically the standard plugin configuration from plugin readme.

The plugin fails to start, log output is as follows:

```
[6.11.2022, 13:19:52] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[6.11.2022, 13:19:52] [HB Supervisor] Started Homebridge v1.5.0 with PID: 946
[6.11.2022, 13:20:00] Loaded config.json with 1 accessories and 1 platforms.
[6.11.2022, 13:20:01] Loaded 0 cached accessories from cachedAccessories.
[6.11.2022, 13:20:01] ---
[6.11.2022, 13:20:01] ====================
[6.11.2022, 13:20:01] ERROR LOADING PLUGIN homebridge-garage-door-wsensor:
[6.11.2022, 13:20:01] Error: Could not locate the bindings file. Tried:
 → /var/lib/homebridge/node_modules/homebridge-garage-door-wsensor/node_modules/rpio/build/rpio.node
 → /var/lib/homebridge/node_modules/homebridge-garage-door-wsensor/node_modules/rpio/build/Debug/rpio.node
 → /var/lib/homebridge/node_modules/homebridge-garage-door-wsensor/node_modules/rpio/build/Release/rpio.node
 → /var/lib/homebridge/node_modules/homebridge-garage-door-wsensor/node_modules/rpio/out/Debug/rpio.node
 → /var/lib/homebridge/node_modules/homebridge-garage-door-wsensor/node_modules/rpio/Debug/rpio.node
 → /var/lib/homebridge/node_modules/homebridge-garage-door-wsensor/node_modules/rpio/out/Release/rpio.node
 → /var/lib/homebridge/node_modules/homebridge-garage-door-wsensor/node_modules/rpio/Release/rpio.node
 → /var/lib/homebridge/node_modules/homebridge-garage-door-wsensor/node_modules/rpio/build/default/rpio.node
 → /var/lib/homebridge/node_modules/homebridge-garage-door-wsensor/node_modules/rpio/compiled/16.18.0/linux/arm/rpio.node
 → /var/lib/homebridge/node_modules/homebridge-garage-door-wsensor/node_modules/rpio/addon-build/release/install-root/rpio.node
 → /var/lib/homebridge/node_modules/homebridge-garage-door-wsensor/node_modules/rpio/addon-build/debug/install-root/rpio.node
 → /var/lib/homebridge/node_modules/homebridge-garage-door-wsensor/node_modules/rpio/addon-build/default/install-root/rpio.node
 → /var/lib/homebridge/node_modules/homebridge-garage-door-wsensor/node_modules/rpio/lib/binding/node-v93-linux-arm/rpio.node
    at bindings (/var/lib/homebridge/node_modules/homebridge-garage-door-wsensor/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/var/lib/homebridge/node_modules/homebridge-garage-door-wsensor/node_modules/rpio/lib/rpio.js:17:34)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/var/lib/homebridge/node_modules/homebridge-garage-door-wsensor/index.js:2:12)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
[6.11.2022, 13:20:01] ====================
[6.11.2022, 13:20:01] No plugin was found for the accessory "Garage Door Opener" in your config.json. Please make sure the corresponding plugin is installed correctly.
[6.11.2022, 13:20:01] Loading 1 platforms...
[6.11.2022, 13:20:01] Loading 1 accessories...
```

Is there anything I can do to make it work? Unfortunately, I’m not a programmer…

Cheers

Jan

**Comment by jph76** [comment]
Nevermind, going for a bike ride and uninstalling and re-installing did the trick. :)
